### ISSUE TITLE
[8.0] tko_fix_mail_private_message_exception: "ValueError: Routing: posting a message without model should be with a parent_id (private mesage)."

### ISSUE THREAD

**Issue by chesucr** [thinkopensolutions/tko-social#12]
Hello. I am working on Odoo 8 and I was configuring an email with IMAP protocol. I allowed the access from external applications on the Gmail configuration. I was getting this error and I have installed you module, but I am still getting the same error. Do you know what is happening??

```
2017-05-16 08:38:34,728 5703 ERROR cdc openerp.addons.fetchmail.fetchmail: Failed to process mail from imap server Gmail IMAP.
Traceback (most recent call last):
  File "/opt/odoo_8/src/linked-addons/fetchmail/fetchmail.py", line 215, in fetch_mail
    context=context)
  File "/opt/odoo_8/src/OCA/OCB/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo_8/src/linked-addons/mail/mail_thread.py", line 1213, in message_process
    routes = self.message_route(cr, uid, msg_txt, msg, model, thread_id, custom_values, context=context)
  File "/opt/odoo_8/src/OCA/OCB/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo_8/src/linked-addons/mail/mail_thread.py", line 1096, in message_route
    update_author=True, assert_model=True, context=context)
  File "/opt/odoo_8/src/OCA/OCB/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo_8/src/linked-addons/tko_fix_mail_private_message_exception/models/mail_thread.py", line 71, in message_route_verify
    context=context)
  File "/opt/odoo_8/src/OCA/OCB/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo_8/src/linked-addons/mail/mail_thread.py", line 850, in message_route_verify
    raise ValueError('Routing: posting a message without model should be with a parent_id (private mesage).')
ValueError: Routing: posting a message without model should be with a parent_id (private mesage).
```

**Comment by chesucr** [comment]
Ah! I have changed some parameters and it works now. It would be nice to write this conditions somewhere

**Comment by chesucr** [comment]
The user settings must be configured by the administrator:

* **Receive Inbox Notifications by Email:** All Messages
* **Messaging Alias:** incoming@mail.com

The "Messaging Alias" cannot be repeated in more than one user

**Comment by cmsalmeida** [comment]
Have you fixed any code?
Or you just did those configs?

**Comment by chesucr** [comment]
I just did those configurations. Finally I didn't need to install the module
